### ISSUE TITLE
onshape

### ISSUE THREAD

**Issue by TechnologyClassroom** [ervanalb/covid19#1]
Thank you for this!  I was looking for these parts under a free culture license and someone linked me to your project.

Onshape adds a layer of difficulty to access the shapes.  Downloading a shape was difficult to find.  I exported the shapes into stl, text, mm, fine, as separate files.  Would you accept a pull request to place them in this repo to make them easier to access?

**Comment by ervanalb** [comment]
absolutely!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
